### PR TITLE
Enable batch retrieval of large number of entities

### PR DESCRIPTION
**Pull request by cpavanrun**
When the number of entity row grows beyond 10.000, one needs to 'manually' start batch retrieving via `client.get` calls. This PR implements changes that allow the `client.get`to do this batch retrieval by default if needed.

Some slightly less clean solutions have been kept to keep old behavior of `num` and `raw` and to have this PR not break existing behavior.

In addition, small tweaks for closing socket and file streams during testing have added (since PyCharm kept complaining about those dangling resources).

### CODE REVIEW

**Comment by cpavanrun** [comment]
Wondering why the build failed.

**Comment by marikaris** [comment]
> Wondering why the build failed.

Our jenkins was too busy and gave a timeout. I restarted it and all is fine now. 

I will look at your code later. I had a discussion with a colleague before about some feature like this, we then agreed that we maybe wanted to move it to some kind of utility tool which we haven't created yet. I will re-discuss it and get back to you later.

**Comment by tommydeboer** [comment]
@cpavanrun This PR slipped under our radar, sorry for the wait. Thanks for the feature + other improvements! :+1: It's good to go and we'll try to have a new release out ASAP.

**Comment by cpavanrun** [comment]
Awesome! Thanks!

**Pull request merged**
